In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style

In [2]:
# def ExpMovingAverage(values, window):
#     weights = np.exp(np.linspace(-1., 0., window))
#     weights /= weights.sum()
#     a =  np.convolve(values, weights, mode='full')[:len(values)]
#     a[:window] = a[window]
#     return a

In [13]:
# 1 minute EURUSD prices
m1 = pd.read_csv(
    'C:/Users/kwilliams/Google Drive/dev/python/projects/DochianChannel/Indicator_Anaylsis/EURUSD1_2015.csv',
    header=None)
m1.columns = ['Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Ticks']
m1['DateTime'] = m1['Date'] + ' ' + m1['Time']
m1['DateTime'] = pd.to_datetime(m1['DateTime'],format='%Y.%m.%d %H:%M')
m1.set_index('DateTime', inplace=True)
#m1.head()
values = m1['Close']

In [7]:
weights = np.exp(np.linspace(-1., 0., 12))

In [10]:
weights

array([ 0.04813882,  0.05272016,  0.05773751,  0.06323236,  0.06925014,
        0.07584064,  0.08305835,  0.09096297,  0.09961986,  0.10910063,
        0.11948368,  0.13085487])

In [11]:
weights.sum()

1.0

In [9]:
weights /= weights.sum()
weights

array([ 0.04813882,  0.05272016,  0.05773751,  0.06323236,  0.06925014,
        0.07584064,  0.08305835,  0.09096297,  0.09961986,  0.10910063,
        0.11948368,  0.13085487])

In [16]:
a =  np.convolve(values, weights, mode='full')[:len(values)]

In [22]:
a[:26]

array([ 0.06291599,  0.13181918,  0.20728129,  0.28991209,  0.38040248,
        0.47951153,  0.58805274,  0.70691846,  0.83708501,  0.97964569,
        1.13578871,  1.30678697,  1.30676522,  1.30675102,  1.30672298,
        1.30673866,  1.306762  ,  1.30675884,  1.30675681,  1.30677565,
        1.30681576,  1.30684634,  1.30684023,  1.3068676 ,  1.30686738,
        1.30684086])